# Generated by Django 4.2.20 on 2025-04-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spots_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('epithet', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='spots_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('epithet', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('spots_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismSystem.spots_1')),
            ],
        ),
        migrations.CreateModel(
            name='spots_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('epithet', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('spots_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismSystem.spots_2')),
            ],
        ),
    ]
