# Generated by Django 5.2.1 on 2025-05-28 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots_2',
            name='spots_1',
        ),
        migrations.RemoveField(
            model_name='spots_3',
            name='spots_1',
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('nature', '自然景观'), ('history', '历史古迹'), ('city', '城市地标'), ('campus', '校园'), ('teaching', '教学楼'), ('office', '办公楼'), ('dorm', '宿舍楼'), ('shop', '商店'), ('restaurant', '饭店'), ('toilet', '洗手间'), ('library', '图书馆'), ('canteen', '食堂'), ('supermarket', '超市'), ('cafe', '咖啡馆')], max_length=30)),
                ('keywords', models.CharField(blank=True, help_text='用逗号分隔', max_length=200)),
                ('epithet', models.CharField(blank=True, max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('cover', models.ImageField(default='TourismSystem/images/default.jpg', upload_to='attraction_covers/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='TourismSystem.attraction')),
            ],
            options={
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='diary_images/')),
                ('rating', models.IntegerField()),
                ('popularity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_modify_rating', models.BooleanField(default=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='TourismSystem.attraction')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'attraction')},
            },
        ),
        migrations.CreateModel(
            name='DiaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TourismSystem.diary')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='TourismSystem.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('diary', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='spots_1',
        ),
        migrations.DeleteModel(
            name='spots_2',
        ),
        migrations.DeleteModel(
            name='spots_3',
        ),
    ]
