# Generated by Django 5.2 on 2025-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0002_remove_spots_2_spots_1_remove_spots_3_spots_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场所名称')),
                ('description', models.TextField(blank=True, verbose_name='场所描述')),
                ('latitude', models.FloatField(null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(null=True, verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='具体地址')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='场所类别')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '场所',
                'verbose_name_plural': '场所',
                'ordering': ['name'],
            },
        ),
    ]
