# Generated by Django 5.2 on 2025-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0003_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔', max_length=200),
        ),
        migrations.AlterField(
            model_name='diary',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
