# Generated by Django 5.2 on 2025-05-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0004_delete_location_diary_diary_id_diary_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together=set(),
        ),
    ]
