# Generated by Django 5.2 on 2025-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0005_alter_diary_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
