# Generated by Django 5.2 on 2025-05-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0007_alter_diary_options_remove_diary_can_modify_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarycomment',
            options={'ordering': ['-created_at'], 'verbose_name': '日记评论', 'verbose_name_plural': '日记评论'},
        ),
        migrations.AddField(
            model_name='diary',
            name='can_modify_rating',
            field=models.BooleanField(default=True, verbose_name='可修改评分'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='diarycomment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_comments', to='TourismSystem.diary'),
        ),
    ]
