# Generated by Django 5.2.1 on 2025-05-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0008_alter_diarycomment_options_diary_can_modify_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_time', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='TourismSystem.attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-view_time'],
                'unique_together': {('user', 'attraction', 'view_time')},
            },
        ),
    ]
