# Generated by Django 5.2 on 2025-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0009_attractionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='diary_videos/', verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='diary',
            name='video_status',
            field=models.CharField(choices=[('pending', '等待生成'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='视频状态'),
        ),
        migrations.AddField(
            model_name='diary',
            name='video_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='视频任务ID'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='category',
            field=models.CharField(choices=[('', '全部类别'), ('natural', '自然景观'), ('campus', '校园'), ('history', '历史古迹'), ('city', '城市地标'), ('teaching', '教学楼'), ('office', '办公楼'), ('dorm', '宿舍楼'), ('shop', '商店'), ('restaurant', '饭店'), ('toilet', '洗手间'), ('library', '图书馆'), ('canteen', '食堂'), ('supermarket', '超市'), ('cafe', '咖啡馆')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='AttractionView',
        ),
    ]
