# Generated by Django 5.2.1 on 2025-06-02 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismSystem', '0010_diary_video_diary_video_status_diary_video_task_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='video',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='video_status',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='video_task_id',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='美食名称')),
                ('restaurant', models.CharField(max_length=100, verbose_name='餐厅/窗口名称')),
                ('cuisine', models.CharField(choices=[('', '全部菜系'), ('sichuan', '川菜'), ('cantonese', '粤菜'), ('hunan', '湘菜'), ('jiangsu', '苏菜'), ('shandong', '鲁菜'), ('zhejiang', '浙菜'), ('anhui', '徽菜'), ('fujian', '闽菜'), ('fast_food', '快餐'), ('snack', '小吃'), ('hotpot', '火锅'), ('bbq', '烧烤'), ('dessert', '甜点'), ('drink', '饮品'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩餐'), ('southeast_asian', '东南亚菜'), ('other', '其他')], default='', max_length=20, verbose_name='菜系')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('popularity', models.IntegerField(default=0, verbose_name='热度')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分数量')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('image', models.ImageField(default='TourismSystem/images/default_food.jpg', upload_to='food_images/', verbose_name='图片')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('keywords', models.CharField(blank=True, help_text='用逗号分隔', max_length=200, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='TourismSystem.attraction', verbose_name='所属景点')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='评分')),
                ('content', models.TextField(blank=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='TourismSystem.food', verbose_name='美食')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '美食评价',
                'verbose_name_plural': '美食评价',
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='TourismSyst_name_314ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['restaurant'], name='TourismSyst_restaur_4b9dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['cuisine'], name='TourismSyst_cuisine_1695bf_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['popularity'], name='TourismSyst_popular_08f827_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['rating'], name='TourismSyst_rating_b11b4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodreview',
            unique_together={('food', 'user')},
        ),
    ]
